module BrandDev
  module Models
    type brand_web_scrape_md_response =
      {
        markdown: String,
        success: BrandDev::Models::BrandWebScrapeMdResponse::success,
        url: String,
        key_metadata: BrandDev::Models::BrandWebScrapeMdResponse::KeyMetadata
      }

    class BrandWebScrapeMdResponse < BrandDev::Internal::Type::BaseModel
      attr_accessor markdown: String

      attr_accessor success: BrandDev::Models::BrandWebScrapeMdResponse::success

      attr_accessor url: String

      attr_reader key_metadata: BrandDev::Models::BrandWebScrapeMdResponse::KeyMetadata?

      def key_metadata=: (
        BrandDev::Models::BrandWebScrapeMdResponse::KeyMetadata
      ) -> BrandDev::Models::BrandWebScrapeMdResponse::KeyMetadata

      def initialize: (
        markdown: String,
        success: BrandDev::Models::BrandWebScrapeMdResponse::success,
        url: String,
        ?key_metadata: BrandDev::Models::BrandWebScrapeMdResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        markdown: String,
        success: BrandDev::Models::BrandWebScrapeMdResponse::success,
        url: String,
        key_metadata: BrandDev::Models::BrandWebScrapeMdResponse::KeyMetadata
      }

      type success = true

      module Success
        extend BrandDev::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[BrandDev::Models::BrandWebScrapeMdResponse::success]
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < BrandDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
