module BrandDev
  module Models
    type brand_web_scrape_images_params =
      {
        url: String,
        enrichment: BrandDev::BrandWebScrapeImagesParams::Enrichment,
        headers: ::Hash[Symbol, String],
        max_age_ms: Integer,
        timeout_ms: Integer,
        wait_for_ms: Integer
      }
      & BrandDev::Internal::Type::request_parameters

    class BrandWebScrapeImagesParams < BrandDev::Internal::Type::BaseModel
      extend BrandDev::Internal::Type::RequestParameters::Converter
      include BrandDev::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_reader enrichment: BrandDev::BrandWebScrapeImagesParams::Enrichment?

      def enrichment=: (
        BrandDev::BrandWebScrapeImagesParams::Enrichment
      ) -> BrandDev::BrandWebScrapeImagesParams::Enrichment

      attr_reader headers: ::Hash[Symbol, String]?

      def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader max_age_ms: Integer?

      def max_age_ms=: (Integer) -> Integer

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      attr_reader wait_for_ms: Integer?

      def wait_for_ms=: (Integer) -> Integer

      def initialize: (
        url: String,
        ?enrichment: BrandDev::BrandWebScrapeImagesParams::Enrichment,
        ?headers: ::Hash[Symbol, String],
        ?max_age_ms: Integer,
        ?timeout_ms: Integer,
        ?wait_for_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        enrichment: BrandDev::BrandWebScrapeImagesParams::Enrichment,
        headers: ::Hash[Symbol, String],
        max_age_ms: Integer,
        timeout_ms: Integer,
        wait_for_ms: Integer,
        request_options: BrandDev::RequestOptions
      }

      type enrichment =
        {
          classification: bool,
          hosted_url: bool,
          max_time_per_ms: Integer,
          resolution: bool
        }

      class Enrichment < BrandDev::Internal::Type::BaseModel
        attr_reader classification: bool?

        def classification=: (bool) -> bool

        attr_reader hosted_url: bool?

        def hosted_url=: (bool) -> bool

        attr_reader max_time_per_ms: Integer?

        def max_time_per_ms=: (Integer) -> Integer

        attr_reader resolution: bool?

        def resolution=: (bool) -> bool

        def initialize: (
          ?classification: bool,
          ?hosted_url: bool,
          ?max_time_per_ms: Integer,
          ?resolution: bool
        ) -> void

        def to_hash: -> {
          classification: bool,
          hosted_url: bool,
          max_time_per_ms: Integer,
          resolution: bool
        }
      end
    end
  end
end
