module BrandDev
  module Resources
    class Brand
      def retrieve: (
        ?domain: String,
        ?force_language: BrandDev::Models::BrandRetrieveParams::force_language,
        ?max_speed: bool,
        ?name: String,
        ?ticker: String,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> BrandDev::Models::BrandRetrieveResponse

      def ai_query: (
        data_to_extract: ::Array[BrandDev::BrandAIQueryParams::DataToExtract],
        domain: String,
        ?specific_pages: BrandDev::BrandAIQueryParams::SpecificPages,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> BrandDev::Models::BrandAIQueryResponse

      def identify_from_transaction: (
        transaction_info: String,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> BrandDev::Models::BrandIdentifyFromTransactionResponse

      def prefetch: (
        domain: String,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> BrandDev::Models::BrandPrefetchResponse

      def retrieve_naics: (
        input: String,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> BrandDev::Models::BrandRetrieveNaicsResponse

      def retrieve_simplified: (
        domain: String,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> BrandDev::Models::BrandRetrieveSimplifiedResponse

      def screenshot: (
        domain: String,
        ?full_screenshot: BrandDev::Models::BrandScreenshotParams::full_screenshot,
        ?request_options: BrandDev::request_opts
      ) -> BrandDev::Models::BrandScreenshotResponse

      def styleguide: (
        domain: String,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> BrandDev::Models::BrandStyleguideResponse

      def initialize: (client: BrandDev::Client) -> void
    end
  end
end
