module BrandDev
  class BrandAIQueryParams = BrandDev::Models::BrandAIQueryParams

  class BrandIdentifyFromTransactionParams = BrandDev::Models::BrandIdentifyFromTransactionParams

  class BrandPrefetchParams = BrandDev::Models::BrandPrefetchParams

  class BrandRetrieveByTickerParams = BrandDev::Models::BrandRetrieveByTickerParams

  class BrandRetrieveNaicsParams = BrandDev::Models::BrandRetrieveNaicsParams

  class BrandRetrieveParams = BrandDev::Models::BrandRetrieveParams

  class BrandSearchParams = BrandDev::Models::BrandSearchParams
end
