module BrandDev
  class BrandAIQueryParams = BrandDev::Models::BrandAIQueryParams

  class BrandIdentifyFromTransactionParams = BrandDev::Models::BrandIdentifyFromTransactionParams

  class BrandPrefetchParams = BrandDev::Models::BrandPrefetchParams

  class BrandRetrieveByEmailParams = BrandDev::Models::BrandRetrieveByEmailParams

  class BrandRetrieveByNameParams = BrandDev::Models::BrandRetrieveByNameParams

  class BrandRetrieveByTickerParams = BrandDev::Models::BrandRetrieveByTickerParams

  class BrandRetrieveNaicsParams = BrandDev::Models::BrandRetrieveNaicsParams

  class BrandRetrieveParams = BrandDev::Models::BrandRetrieveParams

  class BrandRetrieveSimplifiedParams = BrandDev::Models::BrandRetrieveSimplifiedParams

  class BrandScreenshotParams = BrandDev::Models::BrandScreenshotParams

  class BrandStyleguideParams = BrandDev::Models::BrandStyleguideParams
end
